import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthButton from '@/components/AuthButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <nav className="w-full flex justify-center h-16">
          <div className="w-full max-w-4xl flex justify-between items-center p-3 text-sm">
            <div className="ml-auto">
              <AuthButton />
            </div>
          </div>
        </nav>
        <main className="min-h-screen flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
